apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-myqr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-myqr
    app.kubernetes.io/part-of: ci10t-786-0040-app
  name: devfile-sample-myqr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-myqr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-myqr
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0040-tenant/ci10t-786-0040-app/devfile-sample-myqr@sha256:dad7602fb05054aa950356c5e102f3df5601cfd46a7bac65227d85ad68ef3c5c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
